add readme, fail on error

diff --git a/.github/workflows/tests_on_merge_main.yaml b/.github/workflows/tests_on_merge_main.yaml
--- a/.github/workflows/tests_on_merge_main.yaml
+++ b/.github/workflows/tests_on_merge_main.yaml
@@ -60,7 +60,10 @@ jobs:
       - name: Running sql scripts
         run: |
           for file in sql_scripts/*.sql; do
-          psql -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }} -d postgres -a -f "$file"
+            if ! psql -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }} -d postgres -a -f "$file"; then
+                echo "Failed to run $file"
+                exit 1
+            fi
           done
         env:
           PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
